dist: trusty
sudo: required
cache: apt
# addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-5
#    - g++-6
#    - g++-7
# env:
#   matrix:
#     - CXX=g++-5
#     - CXX=g++-6
#     - CXX=g++-7

language: C++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -y -qq;
      sudo apt-get install -y g++-5;
      sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-5  90;
      sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-5  90;
    fi

compiler:
  - g++
  - clang++
install:
  - sh bootstrap.sh
  - mkdir bali-phy-build
script:
  - cd bali-phy-build
  - ../configure --prefix=$HOME/local
  - make -j3 install
  - make check
os:
  - linux
  - osx

