dist: trusty
sudo: required
language: C++
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq                             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y g++-5                          ; fi
      # make sure we're using new gcc tools
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-5  90 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-5  90 ; fi

compiler:
    - g++
    - clang++
install:
    - sh bootstrap.sh
    - mkdir bali-phy-build
script:
    - cd bali-phy-build
    - ../configure --prefix=$HOME/local
    - make -j3 install
    - make check
os:
    - linux
    - osx

