X ~ Normal()
X ~ Normal("\"")
X ~ Normal('"')
X ~ Normal('j')
X ~ Normal("o")
X ~ Normal(0.0)
X ~ Normal(0.0,0.00)
X ~ Normal(0.0 , 0.00)
X ~ Normal(0,1)
X ~ Normal(0:0:[],1)
X ~ Normal(0+(0+0),1)
X ~ Normal(0,"1")
X ~ Normal(0+0-0,1)
X ~ Normal(0+0-(-0),1)
X ~ Normal(0+0- -0,1)
X ~ Normal(-0+0- -0,1)
X ~ Normal(x*y+z*w,1)
X ~ Normal(0 0,1)
Y ~ Normal(x,1)
Y ~ Normal([x],1)
Y ~ Normal([x,x],1)
Y ~ Normal((x,x),1)
Y ~ Normal(N.x,1)
Y ~ Normal((x),1)
Y ~ Normal(x (z y),1)
Y ~ Normal(x z y,1)
Y ~ Normal((,,,) z (z y),1)
Y ~ Normal(Maybe z (z y),1)
