#ifndef TYPE_CONSTANT_H
#define TYPE_CONSTANT_H

enum type_constant {null_type=0,
		    int_type=1,
		    double_type=2,
		    log_double_type=3,
		    char_type=4,
		    index_var_type=5,
		    expression_type=6,
		    operation_type=7,
		    parameter_type=8, 
		    modifiable_type=9,
		    dummy_type=10,
		    trim_type=11,
		    let_type=12,
		    case_type=13,
		    let2_type=14,
		    constructor_type=15,
		    lambda_type=16,
		    lambda2_type=17,
		    unknown_type=18
};

#endif
