#!/bin/sh

### A script for running bali-phy on the Sun Grid Engine (SGE) ###

#------------------------ qsub options: --------------------#
# -V:         Give the job access to shell environment variables
# -S /bin/sh: Use /bin/sh as the shell for the job.
# -cwd:       Execute the job from the current working directory.
# -N <name>   Specify job name

QSUB_ARGS='-V -S /bin/sh -cwd -N bali-phy -l mem_free=2G'

#------------------ Locate the programs --------------------#
QSUB=$(type -p qsub)
BALI_PHY=$(type -p bali-phy)

if [ ! -x "$BALI_PHY" ] ; then
   echo "bali-phy-sge: I can't find 'bali-phy' to run it!"
   echo 'bali-phy-sge: If it is installed, please add it to your $PATH'
   exit 1
fi

if [ ! -x "$QSUB" ] ; then
   echo "bali-phy-sge: I can't find the program 'qsub' to submit your job!"
   echo "bali-phy-sge: Is the Sun Grid Engine installed?"
   exit 1
fi

#------ start the sampler
exec qsub $QSUB_ARGS <<EOF 
#!/bin/sh
exec $BALI_PHY $@
EOF

