#!/usr/bin/perl -w

use strict;
use Cwd 'abs_path';
use File::Basename;
use Archive::Extract;
use File::Path 'make_path';

my $cmd = shift;

my $arg = shift;

if ($cmd eq "install")
{
    print "Installing package $arg...";
    install_package($arg);
    print "done.\n";
}
else
{
    die "I don't understand command '$cmd $arg'.";
}


sub install_package
{
    my $filename = shift;
    $filename = &abs_path($filename);
    my $base_name = &basename($filename);
    my $name = undef;
    my $version = undef;
    if ($base_name =~ /([^_]*)_([^_]*)\.t(|ar\.)gz/)
    {
	$name = $1;
	$version = $2;
    }
    else
    {
	die "Package name '$base_name' doesn't make sense - should be <name>_<version>.tgz";
    }

    my $home = $ENV{"HOME"};
    die "Home directory unset or does not exist!" if (! -d $home);

    my $package_dir = $home."/.local/share/bali-phy/packages/$name/$version/";
    make_path ($package_dir);
    chdir $package_dir;
    $tar->Archive::Tar->new($filename);
    $tar->extract();

    print "$package_dir \n";
}
