#!/usr/bin/env python3

import fileinput
import re
import sys


def main():
    headers = []
    sequences = []

    for line in fileinput.input(encoding="utf-8"):
        if line.startswith(">"):
            headers.append(line)
            sequences.append("")
        else:
            sequences[-1] += re.sub(r"\s+", "", line)

    for header, sequence in zip(headers, sequences):
        sys.stdout.write(header)
        sys.stdout.write(sequence[::-1])
        sys.stdout.write("\n")


if __name__ == "__main__":
    main()
