name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - "*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Setup build environment
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
        fi
        python3 -mpip install meson ninja
    - name: Build
      run: |
        meson build --prefix=$HOME/local --buildtype=release
        ninja -C build install
    - name: Test
      run: |
        cd tests
        python3 run-tests.py bali-phy
    - name: Testiphy
      run: |
        cd
        git clone https://gitlab.com/testiphy/testiphy.git
        cd testiphy
        which bali-phy || true
        ./testiphy bali-phy
